import { RolesMap } from "@/interface"


export const permissionsMap = {
  ViewUsers: '查看用户',
  CreateUser: '创建用户',
  EditUser: '编辑用户',
  DeleteUser: '删除用户',
  ViewRoles: '查看角色',
  CreateRole: '创建角色',
  EditRole: '编辑角色',
  DeleteRole: '删除角色',
  ViewPermissions: '查看权限',
  EditPermissions: '编辑权限',
  AssignPermissions: '分配权限',
  ViewContent: '查看内容',
  CreateContent: '创建内容',
  EditContent: '编辑内容',
  DeleteContent: '删除内容',
  ViewReports: '查看报表',
  GenerateReports: '生成报表',
  ManageSettings: '管理设置',
  BypassPermissions: '绕过权限控制',
  SuperAdmin: '超级管理员权限',
  ManageCarousel: '管理首页轮播图',
  ViewNews: '查看新闻',
  CreateNews: '创建新闻',
  EditNews: '编辑新闻',
  DeleteNews: '删除新闻',
  ViewEpidemicData: '查看瘟疫数据',
  EditEpidemicData: '编辑瘟疫数据',
  DeleteEpidemicData: '删除瘟疫数据',
};
